services:
  - type: web
    runtime: docker
    name: AlphaClaw
    plan: starter
    healthCheckPath: /health
    envVars:
      - key: SETUP_PASSWORD
        sync: false
      - key: OPENCLAW_GATEWAY_TOKEN
        generateValue: true
      - key: WEBHOOK_TOKEN
        generateValue: true
      - key: PORT
        value: 3000
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_BOT_TOKEN_ADMIN
        sync: false
      - key: REDDIT_SESSION
        sync: false
      - key: TWITTER_AUTH_TOKEN
        sync: false
      - key: TWITTER_CT0
        sync: false
    disk:
      name: openclaw-data
      mountPath: /data
      sizeGB: 10
